
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**

        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/**

        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/transactions/**

