
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/banking_user_service
      username: root
      password: 974Akas@
      driver-class-name: com.mysql.cj.jdbc.Driver
   
       
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

