

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/banking_user_service
      username: root
      password: 974Akas@
      driver-class-name: com.mysql.cj.jdbc.Driver
 
       
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gateway:
      routes:
        - id: user_services
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**
        - id: account_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction_service
          uri: http://localhost:8084
          predicates:
            - Path=/transactions/**
